name: pulumi-preview-up

on: [push]

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  preview-up-destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Pulumi CLI so that we can create a GHA pipeline specific Pulumi Stack
        uses: pulumi/action-install-pulumi-cli@v1.0.1

      - name: Create GHA pipeline specific Pulumi Stack
        run: pulumi stack init dev github-$GITHUB_RUN_ID

      - uses: pulumi/actions@v2
        with:
          command: preview
          stack-name: github-$GITHUB_RUN_ID

      - uses: pulumi/actions@v2
        with:
          command: up
          stack-name: github-$GITHUB_RUN_ID

      - uses: pulumi/actions@v2
        with:
          command: destroy
          stack-name: github-$GITHUB_RUN_ID
