name: pulumi-preview-up

on: [push]

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pulumi/actions@v1.2.0
        with:
          command: preview
          stack-name: github-$GITHUB_RUN_ID

  up:
    runs-on: ubuntu-latest
    needs: preview
    steps:
      - uses: actions/checkout@v2

      - uses: pulumi/actions@v1.2.0
        with:
          command: up
          stack-name: github-$GITHUB_RUN_ID

  destroy:
    runs-on: ubuntu-latest
    needs: up
    steps:
      - uses: actions/checkout@v2

      - uses: pulumi/actions@v1.2.0
        with:
          command: destroy
          stack-name: github-$GITHUB_RUN_ID